# Introduction to NumPy

## Exercises:

### 1. Update/Upgrade the NumPy package to the latest version

In [21]:
# Parts 1 and 2 can be executed in Jupyter or the Anacodna Prompt

### 2. Install/Upgrade another package (e.g. Pandas) 

In [3]:
pip install pandas --upgrade

### 3. Import NumPy as <i> np </i>

In [4]:
import numpy as np

### 4. Use the<i> np.array() </i>function to create an array variable - <i>array_hw_1</i> with the numbers 4,5,7 and 10 in it

In [7]:
array_hw_1 = np.array([4,5,7,10])

### 5. Display the new array on screen

In [9]:
print(array_hw_1)

[ 4  5  7 10]


### 6. Create a 2x2 array with the same values as <i> array_hw_1 </i> and display it on the screen

In [13]:
array_hw_2 = np.array([[4,5], [7,10]])

In [14]:
array_hw_2

array([[ 4,  5],
       [ 7, 10]])

### 7. Call the <i> np.mean() </i> function on each array

In [15]:
np.mean(array_hw_1)

6.5

In [16]:
np.mean(array_hw_2)

6.5

### 8. Use the <i> axis </i> argument to find the mean for all the rows of <i> array_hw_2</i>

In [17]:
np.mean(array_hw_2, axis = 1)

array([4.5, 8.5])

### 9. Use the <i>axis</i> argument to find the mean for all the columns of <i>array_hw_2</i>

In [19]:
np.mean(array_hw_2, axis = 0)

array([5.5, 7.5])

### 10. Use the <i> Shift + Tab </i> shorcut on <i> np.mean() </i> to check what possible arguments we can specify. 

### 11. Set the <i> dtype </i> argument equal to <i> np.int </i> and compare the results 

In [20]:
np.mean(array_hw_2, axis = 0, dtype = np.int)

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations