# Generating Data w/ Numpy

In [1]:
import numpy as np

### np.empty(), np.zeros(), np.ones(), np.full()

In [9]:
array_empty = np.empty(shape = (2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array_zeros = np.zeros(shape = (2,3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
array_zeros = np.zeros(shape = (2,3), dtype = np.int8)
array_zeros

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [10]:
array_ones = np.ones(shape = (2,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
array_full = np.full(shape = (2,3), fill_value = 2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])

### "_like" functions

In [13]:
matrix_A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matrix_A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
empty_like_array = np.empty_like(matrix_A)
empty_like_array

array([[4128860, 6029375, 7274573, 7209077],
       [5242996, 6881391, 7602286, 6357069],
       [6357102, 6619239,     114, 3342437]])

In [17]:
array_1s_like = np.ones_like(matrix_A)
array_1s_like

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### np.arange()

In [19]:
list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [23]:
array_rng = np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
array_rng = np.arange(start = 0, stop = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
array_rng = np.arange(start = 0, stop = 30, step = 2.5)
array_rng

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [28]:
array_rng = np.arange(start = 0, stop = 30, step = 2.5, dtype = np.int32)
array_rng

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

## Random Generators

### Defining Random Generators

In [29]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [33]:
array_RG = gen(pcg())
array_RG.normal(size = (5,5))

array([[ 1.14737215,  0.21230966, -1.46645426, -0.81886722, -1.27603016],
       [ 0.24348614,  0.13831767,  0.37506567,  0.02103054, -0.02862265],
       [-0.37540075,  0.06571724,  1.9218007 ,  1.71849037,  0.2328526 ],
       [ 0.64376649,  1.59265857,  1.1351564 , -1.85098179, -0.71860454],
       [-0.22673817, -0.6729751 ,  0.48535638, -1.73427615, -1.15730998]])

In [34]:
#Seed gives the same output
array_RG = gen(pcg(seed = 365))
array_RG.normal(size = (5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [35]:
#Avoid doing this alone
array_RG.normal(size = (5,5))

array([[-0.76065577,  1.48158358,  0.01200258, -0.06846959,  0.25301664],
       [-0.52640788,  0.79613109,  0.28203421,  1.80238008,  0.93932117],
       [-0.53693283, -0.26317689, -1.77723035,  1.14900013, -2.20733915],
       [ 1.54116775, -0.5124932 , -2.14564563,  1.98878673,  0.32208907],
       [-1.2651495 ,  3.2714633 ,  1.78650493, -0.20233675,  0.20427467]])

### Generating Integers, Probabilities and Random Choices

In [38]:
array_RG = gen(pcg(seed = 365))
array_RG.integers(10, size = (5,5))

array([[0, 7, 6, 7, 8],
       [6, 6, 2, 0, 6],
       [3, 0, 3, 7, 9],
       [1, 1, 8, 7, 4],
       [4, 8, 6, 4, 9]], dtype=int64)

In [39]:
array_RG = gen(pcg(seed = 365))
array_RG.integers(low = 10, high = 100, size = (5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]], dtype=int64)

In [40]:
#Between 0 and 1
array_RG = gen(pcg(seed = 365))
array_RG.random(size = (5,5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [43]:
#Specifying the numbers you want to be in an array
array_RG = gen(pcg(seed = 365))
array_RG.choice([1,2,3,4,5], size = (5,5))

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

### Generating Arrays From Known Distributions

https://numpy.org/doc/stable/reference/random/generator

### Applications of Random Generators